### ISSUE TITLE
Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by hortigado** [kamranbekirovyz/versionarte#2]
Hello, good job with the package. I am trying to deploy it using Remote config but I am getting the following error. I followed all the configuration steps and even in Firebase it registers that the json has been read.
![image](https://github.com/kamranbekirovyz/versionarte/assets/42924254/4295e447-49be-4621-8d9a-e247bde835a5)
![image](https://github.com/kamranbekirovyz/versionarte/assets/42924254/64f487c6-37df-4e08-9359-f446cd5124d4)

**Comment by kamranbekirovyz** [comment]
Hi. Thanks for your kind words about the package 🤩

Can you check they type of “versionarte” in Firebase Remote Config? It must be JSON not String.

**Comment by hortigado** [comment]
@kamranbekirovyz  yes, the type is JSON

**Comment by kamranbekirovyz** [comment]
Can you make the `minimumFetchInterval` let’s say, 10 seconds? If it does not help too I’ll need to check this out on my Mac 🙂

**Comment by hortigado** [comment]
@kamranbekirovyz I just tried time default but I get the same error, remote config still logs that if the json is read but for some reason it gets null
![image](https://github.com/kamranbekirovyz/versionarte/assets/42924254/497498fa-348c-4616-a6ec-76a0f8990dc9)
![image](https://github.com/kamranbekirovyz/versionarte/assets/42924254/1d9673a5-aac2-4d82-864b-e2c26ab80c7a)

**Comment by kamranbekirovyz** [comment]
You shouldn’t keep the iOS and macOS keys as empt, because it’ll try to parse it, then throw exception when it couldn’t find keys inside. 

Consider removing them 🙂

**Comment by hortigado** [comment]
@kamranbekirovyz Thanks, that's correct, that solved the problem. Greetings

**Comment by kamranbekirovyz** [comment]
My pleasure! 

Appreciate you using the package, let me know if there is anything on the docs. or on the API that can be improved. 

Also, if you liked the package, refer to your colleagues 🙂🙏
