### ISSUE TITLE
Feature url of new version

### ISSUE THREAD

**Issue by hortigado** [kamranbekirovyz/versionarte#4]
Hi i need put the url to download the new version. It is useful for windows. Thanks
```
/// Represents the status of an application.
class StatusDetails {
  final bool active;
  final Map<String?, dynamic>? message;
  final String? url;
  const StatusDetails({required this.active, required this.message, this.url});

  StatusDetails.fromJson(Map<String, dynamic> json)
      : active = json["active"],
        message = json["message"],
        url = json["url"];

  String? getMessageForLanguage(String code) {
    return message?[code];
  }

  /// Returns a JSON representation of this object.
  Map<String, dynamic> toJson() {
    return {
      "active": active,
      "message": message,
      "url": url,
    };
  }

  @override
  String toString() {
    return toJson().toString();
  }
}

```

**Comment by kamranbekirovyz** [comment]
Hi @hortigado. Thanks for opening the issue. Are you saying that the download URL of the Windows app changes frequently and you want to remotely manage that URL with versionarte too? Is it the behavior of the Windows Store?

**Comment by hortigado** [comment]
@kamranbekirovyz Hello, I'm still new to developing for Windows and I can't decide whether to upload the app to the Microsoft Store; It wouldn't be the best for version control. Now I wanted to use the github release where all versions of the app would be uploaded so the url would be different for each version.

**Comment by kamranbekirovyz** [comment]
> @kamranbekirovyz Hello, I'm still new to developing for Windows and I can't decide whether to upload the app to the Microsoft Store; It wouldn't be the best for version control. Now I wanted to use the github release where all versions of the app would be uploaded so the url would be different for each version.

I see. I'll add url for each `StoreVersioning` so that you can -if needed- add a download url to your each platform. Does it seem to solve your issue?

**Comment by hortigado** [comment]
Yes, thank you, it would also be good if the windows variable was added to properly organize the information. Although I see that the package is not compatible with Windows, I have made it work well, but if the remoteconfig does not work, applying a json url **RestfulVersionarteProvider** in the case of Windows works well.
![image](https://github.com/kamranbekirovyz/versionarte/assets/42924254/ddf9f6cd-f641-4c81-aed1-532d286958f3)

**Comment by kamranbekirovyz** [comment]
@hortigado are you able to add this package and run on Windows? If that's the case, I can add the windows variable then add a note that "Firebase Remote Config version only works for Android, iOS and MacOS, and for the other platforms please use other versionarte providers."

**Comment by hortigado** [comment]
Its correct, work well on windows.

**Comment by kamranbekirovyz** [comment]
> Its correct, work well on windows with rest.

OK. I'll ship this ASAP.

**Comment by kamranbekirovyz** [comment]
@hortigado I've added "download_url" parameter to the JSON and the version 1.1.0 should land soon.

**Comment by hortigado** [comment]
@kamranbekirovyz Thanks good work. Regards

**Comment by kamranbekirovyz** [comment]
My pleasure @hortigado 

versionarte 1.1.0 has been published. With that, you can add "download_url" to the json for each platform and get that with platform.downloadUrl on code side. Let me know if you have any questions.
