### ISSUE TITLE
getting `unknown` for firebase remote config

### ISSUE THREAD

**Issue by alaz-aura** [kamranbekirovyz/versionarte#7]
Hi there, I'm trying to setup a basic usage of this package with firebase remote config. I must be missing something, as I cannot read my firebase config. Any thoughts?

## Initialisation

```
class _MyHomePageState extends State<MyHomePage> {
  VersionarteResult? _versionarteResult;
  // late final VersionarteResult _versionarteResult;

  bool _isChecking = false;

  @override
  void initState() {
    super.initState();

    _checkVersion();
  }

  Future<void> _checkVersion() async {
    setState(() => _isChecking = true);

    final result = await Versionarte.check(
      versionarteProvider: RemoteConfigVersionarteProvider(),
    );
    setState(() {
      _versionarteResult = result;
      _isChecking = false;
    });
}
```

## Widget text
```
Text(
                _versionarteResult?.status.toString() ?? 'No status available',
              )
```

## UI
![Screenshot 2024-10-21 at 9 58 34 PM](https://github.com/user-attachments/assets/e7fd449d-b21f-4cab-8ecb-c4d6739aef47)

**Comment by kamranbekirovyz** [comment]
Hi. Thanks for using the package. The package also prints some yellow logs to the debug console. Can you check them?

**Comment by alaz-aura** [comment]
![Screenshot 2024-10-22 at 10 45 16 AM](https://github.com/user-attachments/assets/50cde110-f83a-466c-9f20-8bb6a7a77f2e)

Here we are. Ok I did not initialize firebase. 

After doing so, the logs now produce:
![Screenshot 2024-10-22 at 10 49 24 AM](https://github.com/user-attachments/assets/e8bd1e89-e7fe-40d5-89c6-342c816f5274)

Looks like a JSON parsing issue in the package? I've used the example JSON provided in the readme.

In firebase remote config console, I can see the fetches reaching firebase, so that proves that connection is successful. 
![Screenshot 2024-10-22 at 10 48 32 AM](https://github.com/user-attachments/assets/f73657fa-8c11-4321-bfc1-8af0aff79167)

**Comment by alaz-aura** [comment]
my bad ... I had an incorrect name for the remote config property. Even though I followed https://github.com/kamranbekirovyz/versionarte/blob/main/firebase_remote_config_setup.md, I somehow ended up with `versionate`

all solved now, I can use those remote config values now! Cheers
